M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Models/Auto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M2C8_DomaciAutomobili.Models
{
    public class Auto
    {
        public int AutoId { get; set; }

        [Required]
        [Display(Name = "Naziv proizvodjaca")]
        [StringLength(20, MinimumLength = 3)]
        [RegularExpression("[A-Z][A-Za-z]*", ErrorMessage = "Prvo slovo mora biti veliko")]
        public string AutoProizvodjac { get; set; }

        [Required]
        [Display(Name = "Naziv modela")]
        [StringLength(20, MinimumLength = 3)]
        [RegularExpression("[A-Z][A-Za-z]*", ErrorMessage = "Prvo slovo mora biti veliko")]
        public string AutoModel { get; set; }

        [Required]
        [Display(Name = "Godiste automobila")]
        public int AutoGod { get; set; }

        [Required]
        [Display(Name = "kubikaza automobila")]
        public int AutoKub { get; set; }

        [Required]
        [Display(Name = "Boja automobila")]
        [StringLength(20, MinimumLength = 3)]
        [RegularExpression("[A-Z][A-Za-z]*", ErrorMessage = "Prvo slovo mora biti veliko")]
        public string AutoBoja { get; set; }

        public TipMotora TipMotora { get; set; }
    }
}

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Models/TipMotora.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M2C8_DomaciAutomobili.Models
{
    public class TipMotora
    {
        public int TipId { get; set; }

        [Required]
        [Display(Name = "Naziv tipa motora")]
        [StringLength(20, MinimumLength =3)]
        [RegularExpression("[A-Z][A-Za-z]*",ErrorMessage ="Prvo slovo mora biti veliko")]
        public string TipNaziv { get; set; }
    }
}

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Controllers/AutoController.cs
using M2C8_DomaciAutomobili.Models;
using M2C8_DomaciAutomobili.Repository;
using M2C8_DomaciAutomobili.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace M2C8_DomaciAutomobili.Controllers
{
    public class AutoController : Controller
    {
        TipMotoraRepo tmrepo = new TipMotoraRepo();
        AutoRepo autoRepo = new AutoRepo();
        // GET: Auto
        public ActionResult Index()
        {
            List<Auto> ListAutomobila = new List<Auto>();
            ListAutomobila = autoRepo.GetAll().ToList();

            return View(ListAutomobila);
        }

        public ActionResult Add()
        {
            AutoTipMotoraViewModel vm = new AutoTipMotoraViewModel() { ListTipMotora=new List<TipMotora>()};
            vm.ListTipMotora = tmrepo.GetAll().ToList();
            return View(vm);
        }

        [HttpPost]
        public ActionResult Add(AutoTipMotoraViewModel AutoTipMotoraViewModel)
        {

            if (!ModelState.IsValid)
            {
                AutoTipMotoraViewModel.ListTipMotora = tmrepo.GetAll().ToList();
                return View(AutoTipMotoraViewModel);
            }
            AutoTipMotoraViewModel.Auto.TipMotora = tmrepo.GetById(AutoTipMotoraViewModel.SelectedTipMotorById);
            if (autoRepo.Create(AutoTipMotoraViewModel.Auto))
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            Auto AutoById = autoRepo.GetById(id);
            AutoTipMotoraViewModel AutoTipMotoraViewModel = new AutoTipMotoraViewModel() { Auto = AutoById, ListTipMotora = tmrepo.GetAll().ToList() };

            return View(AutoTipMotoraViewModel);
        }

        [HttpPost]
        public ActionResult Edit(AutoTipMotoraViewModel AutoTipMotoraViewModel)
        {
            AutoTipMotoraViewModel.Auto.TipMotora = new TipMotora() { TipId = AutoTipMotoraViewModel.SelectedTipMotorById };
            autoRepo.Update(AutoTipMotoraViewModel.Auto);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            autoRepo.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace M2C8_DomaciAutomobili.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Controllers/TipMotoraController.cs
using M2C8_DomaciAutomobili.Models;
using M2C8_DomaciAutomobili.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace M2C8_DomaciAutomobili.Controllers
{
    public class TipMotoraController : Controller
    {
        TipMotoraRepo TipMotoraRepo = new TipMotoraRepo();
        // GET: TipMotora
        public ActionResult Index()
        {
            List<TipMotora> ListTipMotora = new List<TipMotora>();
            ListTipMotora = TipMotoraRepo.GetAll().ToList();
            return View(ListTipMotora);
        }

        public ActionResult Add()
        {

            return View(new TipMotora());
        }

        [HttpPost]
        public ActionResult Add(TipMotora TipMotora)
        {
            if (!ModelState.IsValid)
            {
                return View(TipMotora);
            }
            if (TipMotoraRepo.Create(TipMotora))
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            TipMotora TipMotora = TipMotoraRepo.GetById(id);
            return View(TipMotora);
        }

        [HttpPost]
        public ActionResult Edit(TipMotora TipMotora)
        {
            if (!ModelState.IsValid)
            {
                return View(TipMotora);
            }
            TipMotoraRepo.Update(TipMotora);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            TipMotoraRepo.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/Auto/Add.cshtml
@model M2C8_DomaciAutomobili.ViewModel.AutoTipMotoraViewModel
<h2>Kreiraj novi automobil</h2>
<hr />
@using (Html.BeginForm("Add", "Auto", FormMethod.Post))
{
    <div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoProizvodjac) <br>
            @Html.EditorFor(m => m.Auto.AutoProizvodjac)
            @Html.ValidationMessageFor(m => m.Auto.AutoProizvodjac)
        </div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoModel) <br>
            @Html.EditorFor(m => m.Auto.AutoModel)
            @Html.ValidationMessageFor(m => m.Auto.AutoModel)
        </div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoGod) <br>
            @Html.EditorFor(m => m.Auto.AutoGod)
            @Html.ValidationMessageFor(m => m.Auto.AutoGod)
        </div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoKub) <br>
            @Html.EditorFor(m => m.Auto.AutoKub)
            @Html.ValidationMessageFor(m => m.Auto.AutoKub)
        </div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoBoja) <br>
            @Html.EditorFor(m => m.Auto.AutoBoja)
            @Html.ValidationMessageFor(m => m.Auto.AutoBoja)
        </div>
        <div>
            @Html.Label("Tip Motora") <br>
            <select name="SelectedTipMotorById">
                @foreach (var item in Model.ListTipMotora)
                {
                    <option value="@item.TipId">@item.TipNaziv</option>
                }
            </select>
        </div>
        <div>
            <input type="submit" name="Add" value="Add" />
        </div>
    </div>
}

@Html.ActionLink("Lista automobila", "Index") |
@Html.ActionLink("Lista tipova motora", "Index", "TipMotora")

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/Auto/Edit.cshtml
@model M2C8_DomaciAutomobili.ViewModel.AutoTipMotoraViewModel
<h2>Edit Automobil</h2>
<hr />
@using (Html.BeginForm("Edit", "Auto", FormMethod.Post))
{
    <div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoProizvodjac) <br>
            @Html.EditorFor(m => m.Auto.AutoProizvodjac)
            @Html.ValidationMessageFor(m => m.Auto.AutoProizvodjac)
        </div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoModel) <br>
            @Html.EditorFor(m => m.Auto.AutoModel)
            @Html.ValidationMessageFor(m => m.Auto.AutoModel)
        </div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoGod) <br>
            @Html.EditorFor(m => m.Auto.AutoGod)
            @Html.ValidationMessageFor(m => m.Auto.AutoGod)
        </div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoKub) <br>
            @Html.EditorFor(m => m.Auto.AutoKub)
            @Html.ValidationMessageFor(m => m.Auto.AutoKub)
        </div>
        <div>
            @Html.LabelFor(m => m.Auto.AutoBoja) <br>
            @Html.EditorFor(m => m.Auto.AutoBoja)
            @Html.ValidationMessageFor(m => m.Auto.AutoBoja)
        </div>
        <div>
            @Html.Label("Tip Motora") <br>
            <select name="SelectedTipMotorById">
                @foreach (var item in Model.ListTipMotora)
                {
                    if (item.TipId == Model.Auto.TipMotora.TipId)
                    {
                        <option selected value="@item.TipId">@item.TipNaziv</option>
                    }
                    else
                    {
                        <option value="@item.TipId">@item.TipNaziv</option>
                    }
                }
            </select>
        </div>
        <div>
            <input type="hidden" name="Auto.AutoId" value="@Model.Auto.AutoId" />
        </div>
        <div>
            <input type="submit" name="Edit" value="Edit" />
        </div>
    </div>
}

@Html.ActionLink("Lista automobila", "Index") |
@Html.ActionLink("Lista tipova motora", "Index", "TipMotora")

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/Auto/Index.cshtml
@model IEnumerable<M2C8_DomaciAutomobili.Models.Auto>

<h2>Lista automobila</h2>

<hr />

<table border="1">
    <tr>
        <th> @Html.Label("AutoId")</th>
        <th> @Html.Label("Proizvodjac")</th>
        <th> @Html.Label("Model")</th>
        <th> @Html.Label("Godiste")</th>
        <th> @Html.Label("Kubikaza")</th>
        <th> @Html.Label("Boja")</th>
        <th> @Html.Label("Tip Motora")</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td> @item.AutoId</td>
            <td> @item.AutoProizvodjac</td>
            <td> @item.AutoModel</td>
            <td> @item.AutoGod</td>
            <td> @item.AutoKub</td>
            <td> @item.AutoBoja</td>
            <td> @item.TipMotora.TipNaziv</td>
            <td> @Html.ActionLink("Edit", $"Edit/{item.AutoId}")</td>
            <td> @Html.ActionLink("Delete", $"Delete/{item.AutoId}")</td>
        </tr>
    }
</table>

@Html.ActionLink("Dodaj novi automobil", "Add") |
@Html.ActionLink("Lista tipova motora", "Index","TipMotora")

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/TipMotora/Add.cshtml
@model M2C8_DomaciAutomobili.Models.TipMotora

<h2>Unesite novi tip motora</h2>
<hr />

@using (Html.BeginForm("Add", "TipMotora", FormMethod.Post))
{
    <div>
        <h4>Dodaj novi tip motora</h4>
        <div>
            <div>
                @Html.LabelFor(m => m.TipNaziv)
                @Html.EditorFor(m => m.TipNaziv)
            </div>
            <input type="submit" name="Add" value="Add" />
        </div>
    </div>
}
@Html.ValidationMessageFor(m => m.TipNaziv)

@Html.ActionLink("Home Page", "Index", "Auto") |
@Html.ActionLink("Lista tipova motora", "Index")

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/TipMotora/Edit.cshtml
@model M2C8_DomaciAutomobili.Models.TipMotora

<h2>Edit tip motora</h2>

<hr />


@using (Html.BeginForm("Edit", "TipMotora", FormMethod.Post))
{
    <table border="1">
        <tr>
            <th colspan="2" align="center"> Edit tip motora</th>
        </tr>
        <tr>
            <td> @Html.LabelFor(m => m.TipNaziv)</td>
            <td> @Html.TextBox("TipMotora.TipNaziv", $"{Model.TipNaziv}")</td>
            @Html.ValidationMessageFor(m => m.TipNaziv)
        </tr>
        <tr>
            <td> <input type="hidden" name="TipMotora.TipId" value="@Model.TipId" /> </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" name="Edit" value="Edit" />
            </td>
        </tr>
    </table>
}
@Html.ActionLink("Home Page", "Index", "Auto")
@Html.ActionLink("Dodaj novi tip motora", "Index")

M2 10.cas/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/M2C8 DomaciAutomobili/Views/TipMotora/Index.cshtml
@model IEnumerable<M2C8_DomaciAutomobili.Models.TipMotora>

<h2>Lista tipova motora</h2>

<hr />

<table border="1">
    <tr>
        <th> @Html.Label("Id")</th>
        <th> @Html.Label("Naziv")</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td> @item.TipId</td>
            <td> @item.TipNaziv</td>
            <td> @Html.ActionLink("Edit", $"Edit/{item.TipId}")</td>
            <td> @Html.ActionLink("Delete", $"Delete/{item.TipId}")</td>
        </tr>
    }
</table>

@Html.ActionLink("Home Page", "Index", "Auto") |
@Html.ActionLink("Dodaj novi tip motora", "Add")