M2 08.cas/M2C8 DomaciKnjizara/M2C8 DomaciKnjizara/Models/Bookstore.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace M2C8_DomaciKnjizara.Models
{
    public class Bookstore
    {
        public int Id { get; set; }
        public string Name { get; set; }
              
    }
}

M2 08.cas/M2C8 DomaciKnjizara/M2C8 DomaciKnjizara/Controllers/BookstoreController.cs
using M2C8_DomaciKnjizara.Models;
using M2C8_DomaciKnjizara.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using M2C8_DomaciKnjizara.Repository;

namespace M2C8_DomaciKnjizara.Controllers
{
    public class BookstoreController : Controller
    {
        private BookstoreRepo bookrepo = new BookstoreRepo();
        private GenreRepo genrepo = new GenreRepo();
        // GET: Bookstore
        public ActionResult Index()
        {
            BookGenreViewModel BookGenreViewModel = new BookGenreViewModel();
            BookGenreViewModel.GenreList = genrepo.GetAll().ToList();

            return View(BookGenreViewModel);
        }

        public ActionResult List()
        {
            List<Book> BookList = bookrepo.GetAll().ToList();

            return View(BookList);
        }

        [HttpPost]
        public ActionResult Add(BookGenreViewModel BookGenreViewModel)
        {
            if (bookrepo.Create(BookGenreViewModel.Book))
            {
                return RedirectToAction("List");
            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            bookrepo.Delete(id);
            return RedirectToAction("List");
        }

        public ActionResult Deleted()
        {
            List<Book> BookList = new List<Book>();
            BookList = bookrepo.GetAll().ToList();

            return View(BookList);
        }

        public ActionResult Edit(int id)
        {
            BookGenreViewModel BookGenreViewModel = new BookGenreViewModel();
            BookGenreViewModel.GenreList = genrepo.GetAll().ToList();
            BookGenreViewModel.Book = bookrepo.GetById(id);
            BookGenreViewModel.SelectedGenreId = BookGenreViewModel.Book.Genre.Id;

            return View(BookGenreViewModel);
        }

        [HttpPost]
        public ActionResult Edit(BookGenreViewModel BookGenreViewModel)
        {
            BookGenreViewModel.Book.Genre = new Genre() { Id = BookGenreViewModel.SelectedGenreId };
            bookrepo.Update(BookGenreViewModel.Book);

            return RedirectToAction("List");
        }

        public ActionResult Sort(string BookName, string BookPrice)
        {

            DataTable dt = new DataTable();
            DataSet ds = new DataSet();
            SqlDataAdapter dadapter = new SqlDataAdapter();
            string query = null;
            string connectionString = ConfigurationManager.ConnectionStrings["KnjizaraDbContext"].ConnectionString;
            if (BookName == null && BookPrice == null)
            {
                return RedirectToAction("List");
            }
            else if (BookName != null && BookPrice == null)
            {
                if (BookName == "asc")
                {
                    query = "SELECT * FROM Book JOIN Genre ON Book.GenreId=Genre.GenreId ORDER BY BookName";
                }
                else
                {
                    query = "SELECT * FROM Book JOIN Genre ON Book.GenreId=Genre.GenreId ORDER BY BookName DESC";
                }
                using (SqlConnection con = new SqlConnection(connectionString))
                {
                    using (SqlCommand cmd = con.CreateCommand())
                    {
                        cmd.CommandText = query;
                        dadapter.SelectCommand = cmd;
                        dadapter.Fill(ds, "Book");
                        dt = ds.Tables["Book"];
                        con.Close();
                    }
                }
                List<Book> BookList = new List<Book>();
                foreach (DataRow dataRow in dt.Rows)            // izvuci podatke iz svakog reda tj. zapisa tabele
                {
                    int BookId = int.Parse(dataRow["BookId"].ToString());    // iz svake kolone datog reda izvuci vrednost
                    string BookN = dataRow["BookName"].ToString();
                    int BookP = int.Parse(dataRow["BookPrice"].ToString());
                    bool BookDeleted = bool.Parse(dataRow["BookDeleted"].ToString());
                    Genre g = new Genre
                    {
                        Name = dataRow["GenreName"].ToString()
                    };

                    BookList.Add(new Book(BookId, BookN, BookP, g, BookDeleted));
                }
                return View("List", BookList);
            }
            else if (BookName == null && BookPrice != null)
            {
                if (BookPrice == "asc")
                {
                    query = "SELECT * FROM Book JOIN Genre ON Book.GenreId=Genre.GenreId ORDER BY BookPrice";
                }
                else
                {
                    query = "SELECT * FROM Book JOIN Genre ON Book.GenreId=Genre.GenreId ORDER BY BookPrice DESC";
                }

                using (SqlConnection con = new SqlConnection(connectionString))
                {
                    using (SqlCommand cmd = con.CreateCommand())
                    {
                        cmd.CommandText = query;
                        dadapter.SelectCommand = cmd;
                        dadapter.Fill(ds, "Book");
                        dt = ds.Tables["Book"];
                        con.Close();
                    }
                }
                List<Book> BookList = new List<Book>();
                foreach (DataRow dataRow in dt.Rows)            // izvuci podatke iz svakog reda tj. zapisa tabele
                {
                    int BookId = int.Parse(dataRow["BookId"].ToString());    // iz svake kolone datog reda izvuci vrednost
                    string BookN = dataRow["BookName"].ToString();
                    int BookP = int.Parse(dataRow["BookPrice"].ToString());
                    bool BookDeleted = bool.Parse(dataRow["BookDeleted"].ToString());
                    Genre g = new Genre
                    {
                        Name = dataRow["GenreName"].ToString()
                    };
                    BookList.Add(new Book(BookId, BookN, BookP, g, BookDeleted));
                }
                return View("List", BookList);
            }
            return RedirectToAction("List");
        }
    }
}

M2 08.cas/M2C8 DomaciKnjizara/M2C8 DomaciKnjizara/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using M2C8_DomaciKnjizara.Models;
using M2C8_DomaciKnjizara.Repository;
using M2C8_DomaciKnjizara.ViewModels;

namespace M2C8_DomaciKnjizara.Controllers
{
    public class GenreController : Controller
    {
        private GenreRepo genrepo = new GenreRepo();
        // GET: Genre
        public ActionResult Index()
        {
            BookGenreViewModel BookGenreViewModel = new BookGenreViewModel();
            BookGenreViewModel.GenreList = genrepo.GetAll().ToList();

            return View(BookGenreViewModel);
        }

        public ActionResult Delete(int id)
        {
            genrepo.Delete(id);

            return RedirectToAction("Index");
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(BookGenreViewModel BookGenreViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(BookGenreViewModel);
            }

            if (genrepo.Create(BookGenreViewModel.Genre))
            {
                return RedirectToAction("Index");
            }
            return View();

        }

        public ActionResult Edit(int id)
        {
            Genre genre = genrepo.GetById(id);

            return View(genre);
        }

        [HttpPost]
        public ActionResult Edit(Genre Genre)
        {
            if (ModelState.IsValid)
            {
                genrepo.Update(Genre);

                return RedirectToAction("Index");
                
            }
            return View(Genre);

        }

    }
}

M2 08.cas/M2C8 DomaciKnjizara/M2C8 DomaciKnjizara/Views/Bookstore/Deleted.cshtml
@model IEnumerable<M2C8_DomaciKnjizara.Models.Book>
<hr>
<h1>Showing deleted books</h1>
<hr>
<table border="1">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Genre</th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.Deleted == true)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Price</td>
                <td>@item.Genre.Name</td>
            </tr>
        }
    }
</table>

@Html.ActionLink("Link for homepage", "/Index")

M2 08.cas/M2C8 DomaciKnjizara/M2C8 DomaciKnjizara/Views/Bookstore/Edit.cshtml
@model M2C8_DomaciKnjizara.ViewModels.BookGenreViewModel

<hr />
<h1>Edit book</h1>
<hr />

@using (Html.BeginForm("Edit", "Bookstore", FormMethod.Post))
{
    <table border='1'>
        <tr>
            <th colspan='2'> Edit book </th>
        </tr>
        <tr>
            <td align='left'>Name of book:</td>
            <td valign='middle'>
                @Html.TextBox("Book.Name", $"{Model.Book.Name}")
            </td>
        </tr>
        <tr>
            <td align='left'>Price of book:</td>
            <td valign='middle'>
                <input type='number' name='Book.Price' value="@Model.Book.Price">
            </td>
        </tr>
        <tr>
            <td align='left'>Genre of book:</td>
            <td>
                <select name='SelectedGenreId'>
                    @foreach (var item in Model.GenreList)
                    {
                        if (item.Id == Model.SelectedGenreId)
                        {
                            <option selected value="@item.Id">@item.Name </option>
                        }
                        else
                        {
                            <option value="@item.Id">@item.Name</option>
                        }

                    }
                </select>
            </td>
        </tr>
        <tr>
            <td><input type="hidden" name="Book.Id" value="@Model.Book.Id" /></td>
        </tr>
        <tr>
            <td colspan='2' align='right'>
                <input type='submit' name='add' value='Edit'>
            </td>
        </tr>
    </table>
}

@Html.ActionLink("Show all books", "/List") |
@Html.ActionLink("Show deleted books", "/Deleted")
<br />
@Html.ActionLink("Show all genres", "Index", "Genre") |
@Html.ActionLink("Show deleted genres", "/Bookstore/Deleted") |
@Html.ActionLink("Add new genre", "Add", "Genre")

M2 08.cas/M2C8 DomaciKnjizara/M2C8 DomaciKnjizara/Views/Bookstore/Index.cshtml
@model M2C8_DomaciKnjizara.ViewModels.BookGenreViewModel

<hr />
<h1>Bookstore- Home Page</h1>
<hr />

@using (Html.BeginForm("Add", "Bookstore", FormMethod.Post))
{
    <table border='1'>
        <tr>
            <th colspan='2'> Add new book </th>
        </tr>
        <tr>
            <td align='left'>Name of book:</td>
            <td valign='middle'>
                @Html.TextBox("Book.Name")
            </td>
        </tr>
        <tr>
            <td align='left'>Price of book:</td>
            <td valign='middle'>
                <input type='number' name='Book.Price'>
            </td>
        </tr>
        <tr>
            <td align='left'>Genre of book:</td>
            <td>
                <select name='Book.Genre.Id'>
                    @foreach (var item in Model.GenreList)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td colspan='2' align='right'>
                <input type='submit' name='add' value='Add'>
            </td>
        </tr>
    </table>
}

@Html.ActionLink("Show all books", "/List") |
@Html.ActionLink("Show deleted books", "/Deleted")
<br />
@Html.ActionLink("Show all genres", "Index", "Genre") |
@Html.ActionLink("Add new genre", "Add", "Genre")